$(document).ready(function(){
    $("#p1").click(function(){
        $("#p2").toggle()
        $("#p3").toggle()
        $("#p4").toggle()
        $("#p5").toggle()
        $("#p6").toggle()
        $("#p7").toggle()
        $("#p8").toggle()
        $("#answers").toggle()
    });
})
$(document).ready(function(){        
     $("#answers").click(function(){
        $("#p9").toggle()
        $("#p10").toggle()
        $("#p11").toggle()
        $("#p12").toggle()
        $("#p13").toggle()
        $("#p14").toggle()
        $("#p15").toggle()
     })
}) 
