 $("#p1").click(function(){
    $("#p2").show()
    $("#p3").show()
    $("#p4").show()
    $("#p5").show()
    $("#p6").show()
    $("#p7").show()
    $("#p8").show()
    $("#answers").show()
});

 $("#answers").click(function(){
    $("#p9").show()
    $("#p10").show()
    $("#p11").show()
    $("#p12").show()
    $("#p13").show()
    $("#p14").show()
    $("#p15").show()
 })
